name: ryze_tello
description: A library that provides a high level way for you to interact with your Tello.
version: 1.0.2
homepage: https://github.com/eliaxelang007/Tello-Dart

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
