name: ryze_tello
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/eliaxelang007/Tello-Dart

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
